// ==========================================
// EvoAxis V2
// Machine Master
// ==========================================

const machines = [

    { id: "J-01", name: "Mono Measurment Machine" },
    { id: "J-02", name: "Mono Leath Press Machine" },
    { id: "J-03", name: "Shrinkar Machine" },
    { id: "J-04", name: "End Form MachineE" },
    { id: "J-05", name: "GBD Measurment Machine" },
    { id: "J-06", name: "Laser Marking Machine" },
    { id: "J-07", name: "Jib Crane 3 Ton" },

    { id: "CL-01", name: "Robot Cell-1" },
    { id: "CL-02", name: "Robot Cell-2" },
    { id: "CL-03", name: "Manual Spot Welding Machine-1" },
    { id: "CL-04", name: "Manual Spot Welding Machine-2" },

    { id: "P-1", name: "CNC Pipe Bending Machine" },
    { id: "P-2", name: "CNC Pipe Bending Machine" },
    { id: "P-3", name: "CNC Pipe Bending Machine" },
    { id: "P-4", name: "CNC Pipe Bending Machine" },
    { id: "P-5", name: "CNC Pipe Bending Machine" },

    { id: "P-6", name: "Sizing Machine-A" },
    { id: "P-7", name: "Sizing Machine-B" },
    { id: "P-8", name: "Sizing Machine Logan" },
    { id: "P-9", name: "New Sizing M/C" },
    { id: "P-10", name: "Sizing Machine EP" },

    { id: "P-11", name: "Pipe Cutting Machine" },
    { id: "P-12", name: "Pipe Cutting Machine" },
    { id: "P-13", name: "Pipe Cutting Machine" },
    { id: "P-14", name: "Pipe Cutting Machine" },
    { id: "P-15", name: "Pipe Cutting Machine" },
    { id: "P-16", name: "Pipe Cutting Machine" },

    { id: "P-17", name: "Deburring Machine-A" },
    { id: "P-18", name: "Deburring Machine-B" },
    { id: "P-19", name: "Deburring Machine-B Logan" },

    { id: "P-20", name: "Bench Grinder" },
    { id: "P-21", name: "Auto Band Saw Machine" },
    { id: "P-22", name: "Band Saw Machine" },

    { id: "P-23", name: "Press Machine" },
    { id: "P-24", name: "Press Machine" },

    { id: "CU-1", name: "Pipe and Buffle Stuffing" },
    { id: "CU-2", name: "Leak Testing" },
    { id: "CU-3", name: "Marking" },
    { id: "CU-4", name: "DED" },
    { id: "CU-5", name: "Leak Testing" },
    { id: "CU-6", name: "Marking" },
    { id: "CU-7", name: "Welding" },
    { id: "CU-8", name: "Welding" },
    { id: "CU-9", name: "SPM Vertical SPM" },
    { id: "CU-10", name: "Welding" },
    { id: "CU-11", name: "Welding" },
    { id: "CU-12", name: "Arrow Shell Stuffing Press" },
    { id: "CU-13", name: "Seam Welding" },
    { id: "CU-14", name: "Hydraulic Press" },
    { id: "CU-15", name: "Leak Testing" },
    { id: "CU-16", name: "Marking" },
    { id: "CU-17", name: "Welding" },
    { id: "CU-18", name: "Welding" },
    { id: "CU-19", name: "SPM" },
    { id: "CU-20", name: "Welding" },
    { id: "CU-21", name: "Welding" },
    { id: "CU-22", name: "Tig Welding" },
    { id: "CU-23", name: "Bellow SPM" },
    { id: "CU-24", name: "Welding" },
    { id: "CU-25", name: "Vertical SPM" },
    { id: "CU-26", name: "Welding" },
    { id: "CU-27", name: "Welding" },
    { id: "CU-28", name: "Welding" },
    { id: "CU-29", name: "Welding" },
    { id: "CU-30", name: "Welding" },
    { id: "CU-31", name: "Welding" },
    { id: "CU-32", name: "Leak Testing" },
    { id: "CU-33", name: "Marking" },
    { id: "PR-1", name: "Press - Yangali 250T" },
    { id: "PR-2", name: "Press - Yangali 315T" },
    { id: "PR-3", name: "Press - Yangali 315T" },
    { id: "PR-4", name: "Press - Yangali 400T" },
    { id: "PR-5", name: "Press - EPHL 315T" },
    { id: "PR-6", name: "Press MP-75T" },
    { id: "PR-7", name: "Press-200T" },
    { id: "PR-8", name: "Press-160T" },
    { id: "PR-9", name: "Press-110T" },
    { id: "PR-10", name: "Press-63T" },
    { id: "PR-11", name: "Press-400T" },
    { id: "PR-12", name: "Press-400T" },

    { id: "R-1", name: "Tig Welding" },
    { id: "R-2", name: "Leak Testing" },
    { id: "R-3", name: "Double Seaming" },
    { id: "R-4", name: "Spot Welding" },
    { id: "R-5", name: "Tig Welding" },
    { id: "R-6", name: "Tig Welding" },
    { id: "R-7", name: "Case Stuffing" },
    { id: "R-8", name: "Baffale Stuffing" },
    { id: "R-9", name: "Flange Up" },
    { id: "R-10", name: "Welding" },
    { id: "R-11", name: "Welding" },
    { id: "R-12", name: "Baffale Stuffing" },
    { id: "R-13", name: "Logan Spinner" },
    { id: "R-14", name: "Welding" },
    { id: "R-15", name: "Case Stuffing" },
    { id: "R-16", name: "Flange Up" },
    { id: "R-17", name: "Old Lock Seaming" },
    { id: "R-18", name: "Welding" },
    { id: "R-19", name: "Welding" },
    { id: "R-20", name: "Case Stuffing" },
        { id: "R-21", name: "Welding" },
    { id: "R-22", name: "Leak Testing" },
    { id: "R-23", name: "New Lock Seaming" },
    { id: "R-24", name: "Flange Up" },
    { id: "R-25", name: "Stuffing & Spot Welding" },
    { id: "R-26", name: "Tata Muff" },
    { id: "R-27", name: "Press Machine" },
    { id: "R-28", name: "Spot Welding" },
    { id: "R-29", name: "Stuffing & Spot Welding" },
    { id: "R-30", name: "Welding" },
    { id: "R-31", name: "Welding" },
    { id: "R-32", name: "Welding" },
    { id: "R-33", name: "Case Stuffing" },
    { id: "R-34", name: "Rolling" },
    { id: "R-35", name: "Tig Welding" },
    { id: "R-36", name: "Tig Welding" },
    { id: "R-37", name: "Leak Testing" },
    { id: "R-38", name: "SPM" },
    { id: "R-39", name: "New Spinning" },
    { id: "R-40", name: "Leak Testing" },

    { id: "FML-1", name: "Robot Cell-1" },
    { id: "FML-2", name: "Robot Cell-2" },
    { id: "FML-3", name: "Welding" },
    { id: "FML-4", name: "Welding" },
    { id: "FML-5", name: "Welding" },
    { id: "FML-6", name: "Leak Testing" },
    { id: "FML-7", name: "Marking" },
    { id: "FML-8", name: "Welding" },
    { id: "FML-9", name: "Leak Testing" },
    { id: "FML-10", name: "Marking" },
    { id: "FML-11", name: "Welding" },
    { id: "FML-12", name: "Sizing" },
    { id: "FML-13", name: "Welding" },
    { id: "FML-14", name: "Leak Testing" },
    { id: "FML-15", name: "Marking" },
    { id: "FML-16", name: "Leak Testing" },
    { id: "FML-17", name: "Marking" },
    { id: "FML-18", name: "Marking" },
    { id: "FML-19", name: "Welding" },
    { id: "FML-20", name: "Welding" },
    { id: "FML-21", name: "Welding" },
    { id: "FML-22", name: "Tig Welding" },
    { id: "S201-1", name: "Leak Testing" },
    { id: "S201-2", name: "Marking" },
    { id: "S201-3", name: "Robot" },
    { id: "S201-4", name: "Welding" },
    { id: "S201-5", name: "Welding" },
    { id: "S201-6", name: "Leak Testing" },
    { id: "S201-7", name: "Marking" },
    { id: "S201-8", name: "SPM-2" },
    { id: "S201-9", name: "Welding" },
    { id: "S201-10", name: "SPM-1" },
    { id: "S201-11", name: "Welding" },
    { id: "S201-12", name: "Stud Pressing" },
    { id: "S201-13", name: "Welding" },
    { id: "S201-14", name: "Leak Testing" },
    { id: "S201-15", name: "Marking" },
    { id: "S201-16", name: "Welding" },
    { id: "S201-17", name: "DED" },
    { id: "S201-18", name: "Welding" },
    { id: "S201-19", name: "Robot" },
    { id: "S201-20", name: "Leak Testing" },
    { id: "S201-21", name: "Marking" },
    { id: "S201-22", name: "Welding" },
    { id: "S201-23", name: "Welding" },
    { id: "S201-24", name: "Welding" },
    { id: "S201-25", name: "Welding" },
    { id: "S201-26", name: "Leak Testing" },
    { id: "S201-27", name: "Marking" },
    { id: "S201-28", name: "Welding" },
    { id: "S201-29", name: "Leak Testing" },
    { id: "S201-30", name: "Leak Testing" },
    { id: "S201-31", name: "Marking" },
    { id: "S201-32", name: "Robot" },
    { id: "S201-33", name: "Leak Testing" },
    { id: "S201-34", name: "Marking" },
    { id: "S201-35", name: "Leak Testing" },
    { id: "S201-36", name: "Marking" },
    { id: "S201-37", name: "DED" },
    { id: "S201-38", name: "Welding" },
    { id: "S201-39", name: "Welding" },
    { id: "S201-40", name: "SPM" },
    { id: "S201-41", name: "Welding" },
        { id: "P602-1", name: "Leak Testing" },
    { id: "P602-2", name: "Marking" },
    { id: "P602-3", name: "Welding" },
    { id: "P602-4", name: "Robot" },
    { id: "P602-5", name: "Welding" },
    { id: "P602-6", name: "Welding" },
    { id: "P602-7", name: "SPM" },
    { id: "P602-8", name: "Welding" },

    { id: "SCO-1", name: "Leak Testing" },
    { id: "SCO-2", name: "Marking" },
    { id: "SCO-3", name: "Welding" },
    { id: "SCO-4", name: "Welding" },
    { id: "SCO-5", name: "Welding" },
    { id: "SCO-6", name: "VSPM" },
    { id: "SCO-7", name: "Welding" },
    { id: "SCO-8", name: "Welding" },
    { id: "SCO-9", name: "Welding" },
    { id: "SCO-10", name: "Leak Testing" },
    { id: "SCO-11", name: "Robot" },
    { id: "SCO-12", name: "Welding" },
    { id: "SCO-13", name: "Leak Testing" },
    { id: "SCO-14", name: "Marking" },

    { id: "W150-1", name: "Leak Testing" },
    { id: "W150-2", name: "Marking" },
    { id: "W150-3", name: "Leak Testing" },
    { id: "W150-4", name: "Marking" },
    { id: "W150-5", name: "Welding" },
    { id: "W150-6", name: "DED" },
    { id: "W150-7", name: "Welding" },
    { id: "W150-8", name: "Welding" },
    { id: "W150-9", name: "VSPM" },
    { id: "W150-10", name: "Welding" },
    { id: "W150-11", name: "VSPM" },
    { id: "W150-12", name: "Welding" },
    { id: "W150-13", name: "Welding" },
    { id: "W150-14", name: "Welding" },
    { id: "W150-15", name: "DED" },
    { id: "W150-16", name: "Welding" },
    { id: "W150-17", name: "Welding" },
    { id: "W501-1", name: "Drilling SPM" },
    { id: "W501-2", name: "Leak Testing" },
    { id: "W501-3", name: "Marking" },
    { id: "W501-4", name: "Welding" },
    { id: "W501-5", name: "DED" },
    { id: "W501-6", name: "Welding" },
    { id: "W501-7", name: "Leak Testing" },
    { id: "W501-8", name: "Marking" },
    { id: "W501-9", name: "Welding" },
    { id: "W501-10", name: "Leak Testing" },
    { id: "W501-11", name: "Marking" },
    { id: "W501-12", name: "Welding" },
    { id: "W501-13", name: "Welding" },
    { id: "W501-14", name: "Welding" },
    { id: "W501-15", name: "VSPM" },
    { id: "W501-16", name: "Welding" },
    { id: "W501-17", name: "DED" },
    { id: "W501-18", name: "Welding" },
    { id: "W501-19", name: "Welding" },
    { id: "W501-20", name: "Welding" },
    { id: "W501-21", name: "Welding" },
    { id: "W501-22", name: "Leak Testing" },
    { id: "W501-23", name: "Marking" },
    { id: "W501-24", name: "Welding" },
    { id: "W501-25", name: "Welding" },
    { id: "W501-26", name: "Leak Testing" },
        { id: "W506-1", name: "Welding" },
    { id: "W506-2", name: "Leak Testing" },
    { id: "W506-3", name: "Marking" },
    { id: "W506-4", name: "Welding" },
    { id: "W506-5", name: "Welding" },
    { id: "W506-6", name: "Welding" },
    { id: "W506-7", name: "Welding" },

    { id: "UBC-1", name: "Robo Cell" },
    { id: "UBC-2", name: "Leak Testing" },
    { id: "UBC-3", name: "Leak Testing & Engraving" },
    { id: "UBC-4", name: "Manual Welding Machine" },
    { id: "UBC-5", name: "Leak Testing & Engraving" },

    { id: "SO-01", name: "Robo Cell" },
    { id: "SO-02", name: "Rotary SPM-1" },
    { id: "SO-03", name: "Rotary SPM-2" },
    { id: "SO-04", name: "DED" },
    { id: "SO-05", name: "Manual Welding Machine - 1" },
    { id: "SO-06", name: "Manual Welding Machine - 2" },
    { id: "SO-07", name: "Manual Welding Machine - 3" },
    { id: "SO-08", name: "Leak Testing & Engraving" },

    { id: "ES-01", name: "Robo Cell" },
    { id: "ES-02", name: "DED-1" },
    { id: "ES-03", name: "DED-2" },
    { id: "ES-04", name: "Positioner Welding SPM" },

    { id: "UCA-1", name: "Surfacing Machine" },
    { id: "UCA-2", name: "Robo Cell-1" },
    { id: "UCA-3", name: "Metering Machine" },
    { id: "UCA-4", name: "Robo Cell-2" },
    { id: "UCA-5", name: "Robo Cell-3" },
    { id: "UCA-6", name: "Manual Welding Machine" },
    { id: "UCA-7", name: "Engraving Machine" },

    { id: "LCA-1", name: "Robo Cell-1" },
    { id: "LCA-2", name: "Metering Machine" },
    { id: "LCA-3", name: "Robo Cell-2" },
    { id: "LCA-4", name: "Robo Cell-3" },
    { id: "LCA-5", name: "Manual Welding Machine-1" },
    { id: "LCA-6", name: "Manual Welding Machine-2" },
    { id: "LCA-7", name: "Engraving Machine" },

    { id: "YA-01", name: "Manual Welding Machine-1" },
    { id: "YA-02", name: "Manual Welding Machine-2" },
    { id: "YA-03", name: "Manual Welding Machine-3" },
    { id: "YA-04", name: "Manual Welding Machine-4" },
    { id: "YA-05", name: "Surface Facing" },
    { id: "YA-06", name: "Leak Testing" },

    { id: "NLCA-01", name: "Robo Cell-1" },
    { id: "NLCA-02", name: "Metering Machine" },
    { id: "NLCA-03", name: "Robo Cell-2" },
    { id: "NLCA-04", name: "Manual Welding Machine" },
    { id: "NLCA-05", name: "Engraving Machine" },

    { id: "NUCA-01", name: "Robo Cell-1" },
    { id: "NUCA-02", name: "Metering Machine" },
    { id: "NUCA-03", name: "Robo Cell-2" },
    { id: "NUCA-04", name: "Manual Welding Machine" },
    { id: "NUCA-05", name: "Engraving Machine" },

    { id: "U-01", name: "Diesel Generator Set-1010KVA" },
    { id: "U-02", name: "Air Compressor-GA-90" },
    { id: "U-03", name: "Air Compressor-GA75" },
    { id: "U-04", name: "Cooling Tower" },
    { id: "U-05", name: "Handpallets - 1" },
    { id: "U-06", name: "Handpallets - 2" },
    { id: "U-07", name: "Handpallets - 3" }

];